### ISSUE TITLE
Lipo dependency is broken

### ISSUE THREAD

**Issue by totakoko** [ladjs/nodemailer-base64-to-s3#10]
It seems that this plugin no longer works because it depends on the Lipo API which has apparently gone offline.

After two minutes, it throws the error `request to https://api.lipo.io/ failed, reason: connect ETIMEDOUT 159.203.124.62:443`.

Is there any plan to remove the Lipo dependency?

**Comment by titanism** [comment]
v4.0.0 released (which resolves this issue - please also make sure you are on Node >= 14 if you use this version)

https://github.com/forwardemail/nodemailer-base64-to-s3/releases/tag/v4.0.0

**We've also released a backported fix as well as v3.0.3 which should work in older versions of Node >= 12.13**

https://github.com/forwardemail/nodemailer-base64-to-s3/releases/tag/v3.0.3
