### ISSUE TITLE
Check if file exists before uploading (use caching as well)

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/nodemailer-base64-to-s3#3]

**Comment by shayded-exe** [comment]
Any update on this? IMHO this plugin is unusable in production without caching. Unless I'm mistaken, right now it uploads the images every single time an email is sent.

**Comment by niftylettuce** [comment]
I'm incredibly spread thin right now but I will try my best, this among other items in Lad stack are high priority.  If someone submits a PR I will gladly review.

**Comment by niftylettuce** [comment]
To anyone reading - there's an open bug bounty for this in the amount of $50 currently, see https://github.com/niftylettuce/bug-bounties/issues/3

**Comment by niftylettuce** [comment]
I've added this in the latest release, v3.0.0.

Also there are two new options, `fallbackDir` and `fallbackPrefix`.  See the updated README or reference [Lad](https://lad.js.org)'s implementation for further insight.
